name: flutter_nfc
description: This is flutter plugin for accessing the NFC features on Android and iOS.
version: 1.0.0
author: Sukawit Charoendet <sukawit.ch@hotmail.com>
homepage: https://github.com/skwcrd/flutter_nfc

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  convert: ^3.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  test:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.skwcrd.flutter_nfc
        pluginClass: FlutterNfcPlugin
      ios:
        pluginClass: FlutterNfcPlugin